include(CMakeFindDependencyMacro)

if(NOT TARGET asynqro::asynqro)
    include("${CMAKE_CURRENT_LIST_DIR}/asynqro-targets.cmake")
    find_dependency(Threads REQUIRED)
    if (ASYNQRO_QT_SUPPORT)
        find_dependency(Qt5Core CONFIG REQUIRED)
        find_dependency(Qt5Concurrent CONFIG REQUIRED)
        target_link_libraries(asynqro::asynqro INTERFACE Qt5::Core Qt5::Concurrent)
        target_compile_definitions(asynqro::asynqro INTERFACE ASYNQRO_QT_SUPPORT)
        message("-- asynqro: Qt support enabled")
    endif()
endif()
